### ISSUE TITLE
Clarify license of elmer

### ISSUE THREAD

**Issue by daccle** [the-gigi/elmer#1]
Hi Gigi!

Could you please clarify the license of elmer? We would like to use some functions of your code and add them to our own fabfile, but we are not sure if this usage permissible.

Best, Daniel

**Comment by the-gigi** [comment]
Hi Daniel,
Yes, usage is permissble. Added a MIT license.
https://github.com/the-gigi/elmer/issues/1

Enjoy, Gigi
